import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  th: {
    'nav.dashboard': 'หน้าหลัก',
    'nav.attendance': 'เข้างาน',
    'nav.leave': 'ลางาน', 
    'nav.standup': 'รายงานประจำเดือน',
    'nav.menu': 'เมนู',
    'header.logout': 'ออกจากระบบ',
    'dashboard.welcome': 'ยินดีต้อนรับ',
    'dashboard.overview': 'ภาพรวมวันนี้ของคุณ',
    'dashboard.todayAttendance': 'เวลาเข้างานวันนี้',
    'dashboard.thisMonthLeave': 'วันลาพักร้อนเดือนนี้',
    'dashboard.recentStandups': 'รายงานประจำวันนี้',
    'standup.today': 'วันนี้',
    'standup.blockers': 'ปัญหาที่พบ',
    'dashboard.noAttendance':'ยังไม่ได้เข้างาน',
    'dashboard.time':'ครั้ง',
    'dashboard.workday':'วันมาทำงาน',
    'dashboard.lateday':'วันมาสาย',
    'dashboard.lastsevenday':'วัน (เดือนล่าสุด)',
    'dashboard.absent': 'วันขาดงาน',
    'leave.sick':'ลาป่วย',
    'leave.personal':'ลากิจ',
    'leave.annual':'ลาพักร้อน',
    'leave.day':'วัน',
    'status.approve':'อนุมัติ',
    'status.pending':'รออนุมัติ',
    'status.reject':'ปฏิเสธ',
    'status.present':'เข้างาน',
    'status.late':'สาย',
    'status.absent':'ขาด',
    'title.attendance':'เข้างาน',
    'title.leave':'ลางาน',
    'title.date':'วันที่',
    'title.startTime':'เวลาเข้า',
    'title.outTime':'เวลาออก',
    'title.workhour':'ชั่วโมงทำงาน',
    'title.status':'สถานะ',
    'title.type':'ประเภท',
    'title.startDate':'วันที่',
    'title.endDate':'วันสิ้นสุด',
    'title.amountDay':'จำนวนวัน',
    'title.reason': 'เหตุผล',
    'attendance.hour':'ชั่วโมง',
    'standup.searchTitle':'ค้นหารายงานประจำเดือน',
    'standup.searchDay':'ระบุวันที่',
    'standup.searchMonth':'เลือกเดือน/ปี',
    'standup.list':'รายการ',
    'standup.search':'ค้นหา',
    'standup.clear':'เคลียร์',
    'page.previous': 'ก่อนหน้า',
    'employee.title': 'ข้อมูลพนักงาน',
    'employee.formTitle': 'กรอกข้อมูลพนักงาน',
    'employee.code': 'รหัส',
    'employee.codePlaceholder': 'กรอกรหัสพนักงาน',
    'employee.status': 'สถานะ',
    'employee.statusActive': 'ใช้งาน',
    'employee.statusInactive': 'ไม่ใช้งาน',
    'employee.statusResigned': 'ลาออก',
    'employee.type': 'ประเภทพนักงาน',
    'employee.typePlaceholder': 'เลือกประเภทพนักงาน',
    'employee.typeFulltime': 'พนักงานประจำ',
    'employee.typeParttime': 'พนักงานชั่วคราว',
    'employee.typeContract': 'พนักงานสัญญาจ้าง',
    'employee.typeInternship': 'ฝึกงาน',
    'employee.titleTh': 'คำนำหน้า',
    'employee.titlePlaceholder': 'เลือกคำนำหน้า',
    'employee.firstNameTh': 'ชื่อ',
    'employee.firstNameThPlaceholder': 'กรอกชื่อ',
    'employee.lastNameTh': 'นามสกุล',
    'employee.lastNameThPlaceholder': 'กรอกนามสกุล',
    'employee.nicknameTh': 'ชื่อเล่น',
    'employee.nicknameThPlaceholder': 'กรอกชื่อเล่น',
    'employee.firstNameEn': 'First Name',
    'employee.firstNameEnPlaceholder': 'Enter first name',
    'employee.lastNameEn': 'Last Name',
    'employee.lastNameEnPlaceholder': 'Enter last name',
    'employee.nicknameEn': 'Nickname',
    'employee.nicknameEnPlaceholder': 'Enter nickname',
    'employee.gender': 'เพศ',
    'employee.genderPlaceholder': 'เลือกเพศ',
    'employee.genderMale': 'ชาย',
    'employee.genderFemale': 'หญิง',
    'employee.genderOther': 'อื่นๆ',
    'employee.maritalStatus': 'สถานะภาพสมรส',
    'employee.maritalStatusPlaceholder': 'เลือกสถานะภาพสมรส',
    'employee.maritalSingle': 'โสด',
    'employee.maritalMarried': 'สมรส',
    'employee.maritalDivorced': 'หย่าร้าง',
    'employee.maritalWidowed': 'หม้าย',
    'employee.ethnicity': 'เชื้อชาติ',
    'employee.ethnicityPlaceholder': 'กรอกเชื้อชาติ',
    'employee.nationality': 'สัญชาติ',
    'employee.nationalityPlaceholder': 'กรอกสัญชาติ',
    'employee.bloodType': 'หมู่เลือด',
    'employee.bloodTypePlaceholder': 'เลือกหมู่เลือด',
    'employee.weight': 'น้ำหนัก (กก.)',
    'employee.weightPlaceholder': 'กรอกน้ำหนัก',
    'employee.height': 'ส่วนสูง (ซม.)',
    'employee.heightPlaceholder': 'กรอกส่วนสูง',
    'employee.militaryStatus': 'สภาพเกณฑ์ทหาร',
    'employee.militaryStatusPlaceholder': 'เลือกสภาพเกณฑ์ทหาร',
    'employee.militaryExempt': 'ได้รับการยกเว้น',
    'employee.militaryCompleted': 'ผ่านการเกณฑ์ทหาร',
    'employee.militaryNotApplicable': 'ไม่อยู่ในเกณฑ์',
    'employee.religion': 'ศาสนา',
    'employee.religionPlaceholder': 'เลือกศาสนา',
    'employee.religionBuddhism': 'พุทธ',
    'employee.religionChristianity': 'คริสต์',
    'employee.religionIslam': 'อิสลาม',
    'employee.religionHinduism': 'ฮินดู',
    'employee.religionOther': 'อื่นๆ',
    'employee.save': 'บันทึก',
    'employee.reset': 'ล้างข้อมูล',
    'employee.success': 'สำเร็จ',
    'employee.savedSuccess': 'บันทึกข้อมูลพนักงานเรียบร้อยแล้ว',
    'employee.error': 'ข้อผิดพลาด',
    'employee.requiredFields': 'กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน',
    'nav.employee': 'ข้อมูลพนักงาน',
    'employee.listTitle': 'รายชื่อพนักงาน',
    'employee.addNew': 'เพิ่มพนักงานใหม่',
    'employee.editTitle': 'แก้ไขข้อมูลพนักงาน',
    'employee.back': 'กลับ',
    'employee.searchPlaceholder': 'ค้นหาด้วยรหัส, ชื่อ หรือนามสกุล...',
    'employee.total': 'ทั้งหมด',
    'employee.loading': 'กำลังโหลด...',
    'employee.noData': 'ยังไม่มีข้อมูลพนักงาน',
    'employee.noResults': 'ไม่พบผลลัพธ์ที่ค้นหา',
    'employee.fullName': 'ชื่อ-นามสกุล',
    'employee.nickname': 'ชื่อเล่น',
    'employee.actions': 'จัดการ',
    'employee.deleteConfirmTitle': 'ยืนยันการลบ',
    'employee.deleteConfirmMessage': 'คุณแน่ใจหรือไม่ว่าต้องการลบพนักงานคนนี้?',
    'employee.cancel': 'ยกเลิก',
    'employee.delete': 'ลบ',
    'employee.deleteSuccess': 'ลบข้อมูลพนักงานเรียบร้อยแล้ว',
    'employee.deleteError': 'เกิดข้อผิดพลาดในการลบข้อมูล',
    'employee.fetchError': 'เกิดข้อผิดพลาดในการโหลดข้อมูล',
    'employee.saveError': 'เกิดข้อผิดพลาดในการบันทึกข้อมูล',
    'employee.updateSuccess': 'แก้ไขข้อมูลพนักงานเรียบร้อยแล้ว',
    'employee.saving': 'กำลังบันทึก...',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.attendance': 'Attendance',
    'nav.leave': 'Leave',
    'nav.standup': 'Stand-up',
    'nav.menu': 'Menu',
    'header.logout': 'Logout',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Your overview for today',
    'dashboard.todayAttendance': 'Today\'s Attendance',
    'dashboard.thisMonthLeave': 'This Month\'s Leave',
    'dashboard.recentStandups': 'Today Stand-ups',
    'standup.today': 'Today',
    'standup.blockers': 'Blockers',
    'dashboard.noAttendance':'Not Yet Checked In',
    'dashboard.time':'Times',
    'dashboard.workday':'Work Days',
    'dashboard.lateday':'Late Days',
    'dashboard.lastsevenday':'Days (Last 7 Days)',
    'dashboard.absent': 'Absent Days',
    'leave.sick':'Sick',
    'leave.personal':'Personal',
    'leave.annual':'Annual',
    'leave.day':'Day',
    'status.approve':'Approved',
    'status.pending':'Pending',
    'status.reject':'Reject',
    'status.present':'Present',
    'status.late':'Late',
    'status.absent':'Absent',
    'title.attendance':'Attendance',
    'title.leave':'Leave',
    'title.standup':'Stand-ups (Latest month)',
    'title.date':'Date',
    'title.startTime':'Check In',
    'title.outTime':'Check Out',
    'title.workhour':'Work Hours',
    'title.status':'Status',
    'title.type':'Type',
    'title.startDate':'Date',
    'title.endDate':'End Date',
    'title.amountDay':'Days',
    'title.reason': 'Reason',
    'attendance.hour':'Hours',
    'standup.searchTitle':'Search For Stand-ups',
    'standup.searchDay':'Type Date',
    'standup.searchMonth':'Choose Month/Year',
    'standup.list':'Lists',
    'standup.search':'Search',
    'standup.clear':'Clear',
    'employee.title': 'Employee Information',
    'employee.formTitle': 'Employee Registration Form',
    'employee.code': 'Code',
    'employee.codePlaceholder': 'Enter employee code',
    'employee.status': 'Status',
    'employee.statusActive': 'Active',
    'employee.statusInactive': 'Inactive',
    'employee.statusResigned': 'Resigned',
    'employee.type': 'Employee Type',
    'employee.typePlaceholder': 'Select employee type',
    'employee.typeFulltime': 'Full-time',
    'employee.typeParttime': 'Part-time',
    'employee.typeContract': 'Contract',
    'employee.typeInternship': 'Internship',
    'employee.titleTh': 'Title (Thai)',
    'employee.titlePlaceholder': 'Select title',
    'employee.firstNameTh': 'First Name (Thai)',
    'employee.firstNameThPlaceholder': 'Enter first name',
    'employee.lastNameTh': 'Last Name (Thai)',
    'employee.lastNameThPlaceholder': 'Enter last name',
    'employee.nicknameTh': 'Nickname (Thai)',
    'employee.nicknameThPlaceholder': 'Enter nickname',
    'employee.firstNameEn': 'First Name',
    'employee.firstNameEnPlaceholder': 'Enter first name',
    'employee.lastNameEn': 'Last Name',
    'employee.lastNameEnPlaceholder': 'Enter last name',
    'employee.nicknameEn': 'Nickname',
    'employee.nicknameEnPlaceholder': 'Enter nickname',
    'employee.gender': 'Gender',
    'employee.genderPlaceholder': 'Select gender',
    'employee.genderMale': 'Male',
    'employee.genderFemale': 'Female',
    'employee.genderOther': 'Other',
    'employee.maritalStatus': 'Marital Status',
    'employee.maritalStatusPlaceholder': 'Select marital status',
    'employee.maritalSingle': 'Single',
    'employee.maritalMarried': 'Married',
    'employee.maritalDivorced': 'Divorced',
    'employee.maritalWidowed': 'Widowed',
    'employee.ethnicity': 'Ethnicity',
    'employee.ethnicityPlaceholder': 'Enter ethnicity',
    'employee.nationality': 'Nationality',
    'employee.nationalityPlaceholder': 'Enter nationality',
    'employee.bloodType': 'Blood Type',
    'employee.bloodTypePlaceholder': 'Select blood type',
    'employee.weight': 'Weight (kg)',
    'employee.weightPlaceholder': 'Enter weight',
    'employee.height': 'Height (cm)',
    'employee.heightPlaceholder': 'Enter height',
    'employee.militaryStatus': 'Military Status',
    'employee.militaryStatusPlaceholder': 'Select military status',
    'employee.militaryExempt': 'Exempt',
    'employee.militaryCompleted': 'Completed',
    'employee.militaryNotApplicable': 'Not Applicable',
    'employee.religion': 'Religion',
    'employee.religionPlaceholder': 'Select religion',
    'employee.religionBuddhism': 'Buddhism',
    'employee.religionChristianity': 'Christianity',
    'employee.religionIslam': 'Islam',
    'employee.religionHinduism': 'Hinduism',
    'employee.religionOther': 'Other',
    'employee.save': 'Save',
    'employee.reset': 'Reset',
    'employee.success': 'Success',
    'employee.savedSuccess': 'Employee information saved successfully',
    'employee.error': 'Error',
    'employee.requiredFields': 'Please fill in all required fields',
    'nav.employee': 'Employee Info',
    'employee.listTitle': 'Employee List',
    'employee.addNew': 'Add New Employee',
    'employee.editTitle': 'Edit Employee',
    'employee.back': 'Back',
    'employee.searchPlaceholder': 'Search by code, name or surname...',
    'employee.total': 'Total',
    'employee.loading': 'Loading...',
    'employee.noData': 'No employee data yet',
    'employee.noResults': 'No results found',
    'employee.fullName': 'Full Name',
    'employee.nickname': 'Nickname',
    'employee.actions': 'Actions',
    'employee.deleteConfirmTitle': 'Confirm Delete',
    'employee.deleteConfirmMessage': 'Are you sure you want to delete this employee?',
    'employee.cancel': 'Cancel',
    'employee.delete': 'Delete',
    'employee.deleteSuccess': 'Employee deleted successfully',
    'employee.deleteError': 'Error deleting employee',
    'employee.fetchError': 'Error loading data',
    'employee.saveError': 'Error saving data',
    'employee.updateSuccess': 'Employee updated successfully',
    'employee.saving': 'Saving...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('th');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['th']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};